site_name: Описание сервиса "Axolotls"
nav:
 - Home: index.md
# - Professions:
#     - "mining engineering": professions/mining_engineering.md
#     - "picking herbs": professions/picking_herbs.md
 - videos-of-user:
     - "view": video-of-user/view.md
     - "list": video-of-user/list.md
 - link-of-videos:
     - "view": videos/view.md
     - "list": videos/list.md


theme:
 name: material
